name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

concurrency:
  group: mkdocs-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip3 install -U -r requirements.txt
      - run: mkdocs gh-deploy --force
